production:
    APIKey: API_KEY
    ApplicationSecret: APP_SECRET
test:
    APIKey: 354344414965644
    ApplicationSecret: 052ac8832ceab1bfdc527cc13af560c4
development:
    APIKey: 354344414965644
    ApplicationSecret: 052ac8832ceab1bfdc527cc13af560c4
